# Simple mapping example for Elite Dangerous
bindings:
  - input: "x55.axes.0"
    target: "axis:AXIS_X"
    props:
      invert: false
      scale: 1.0
  - input: "x55.axes.1"
    target: "axis:AXIS_Y"
    props:
      invert: true
      scale: 1.0
  - input: "x55.axes.2"
    target: "axis:AXIS_RZ"
    props:
      invert: false
      scale: 1.0
  - input: "x55.button.0"
    target: "button:1"
  - input: "x55.button.1"
    target: "button:2"
  - input: "x55.button.2"
    target: "button:3"
  - input: "x55.button.3"
    target: "button:4"
  - input: "x55.button.4"
    target: "button:5"
  - input: "x55.button.5"
    target: "button:6"
  - input: "x55.button.6"
    target: "button:7"
  - input: "x55.button.7"
    target: "button:8"
  - input: "x55.button.8"
    target: "button:9"
  - input: "x55.button.9"
    target: "button:10"
  - input: "x55.button.10"
    target: "button:11"
  - input: "x55.button.11"
    target: "button:12"
  - input: "x55.button.12"
    target: "button:13"
  - input: "x55.button.13"
    target: "button:14"
  - input: "x55.hat.0"
    target: "pov:0"
  
  # CH Throttle - 1 throttle axis and 12 buttons
  - input: "ch_throttle.axes.0"
    target: "axis:AXIS_Z"
    props:
      invert: true
      scale: 1.0
  - input: "ch_throttle.button.0"
    target: "button:15"
  - input: "ch_throttle.button.1"
    target: "button:16"
  - input: "ch_throttle.button.2"
    target: "button:17"
  - input: "ch_throttle.button.3"
    target: "button:18"
  - input: "ch_throttle.button.4"
    target: "button:19"
  - input: "ch_throttle.button.5"
    target: "button:20"
  - input: "ch_throttle.button.6"
    target: "button:21"
  - input: "ch_throttle.button.7"
    target: "button:22"
  - input: "ch_throttle.button.8"
    target: "button:23"
  - input: "ch_throttle.button.9"
    target: "button:24"
  - input: "ch_throttle.button.10"
    target: "button:25"
  - input: "ch_throttle.button.11"
    target: "button:26"
  
  # Flight Panel switches - toggle mode (momentary pulse on change)
  - input: "flightpanel.switch.5"
    target: "button:27"
    props:
      mode: "toggle"
      pulse_ms: 100

  - input: "flightpanel.switch.12"
    target: "button:28"
    props:
      mode: "toggle"
      pulse_ms: 100

  - input: "flightpanel.switch.18"
    target: "button:29"
    props:
      mode: "toggle"
      pulse_ms: 100
      trigger: on_press

  - input: "flightpanel.switch.19"
    target: "button:30"
    props:
      mode: "toggle"
      pulse_ms: 100
      trigger: on_press
  
  # Flight Panel switches - direct mode (button follows switch state)
  - inputs: 
      - "flightpanel.switch.0"
      - "flightpanel.switch.1"
    target: "button:31"
    props:
      mode: "toggle"
      pulse_ms: 100
